name: bett_box
description: A multi-platform proxy client based on Mihomo, simple and easy to use, open-source and ad-free.
publish_to: 'none'
version: 1.14.11+2026022715
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.5.4
  window_manager: ^0.5.1
  dynamic_color: ^1.8.1
  vclibs: ^0.1.3
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.5.1
  json_annotation: ^4.9.0
  file_picker: ^8.3.7
  mobile_scanner: ^7.2.0
  app_links: ^7.0.0
  win32_registry: ^2.0.0
  tray_manager: ^0.5.2
  collection: ^1.18.0
  animations: ^2.1.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.1
  webdav_client: ^1.2.2
  dio: ^5.9.1
  win32: ^5.15.0
  ffi: ^2.2.0
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  archive: ^3.6.1
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^12.3.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.4.0+2
  yaml: ^3.1.2
  connectivity_plus: ^7.0.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  material_color_utilities: ^0.11.1
  flutter_js: ^0.8.7
  flutter_svg: ^2.2.3
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.7
  flutter_acrylic: ^1.1.4
  sentry_flutter: ^9.14.0
  google_nav_bar: ^5.0.7
  wakelock_plus: ^1.4.0
  flutter_spinkit: ^5.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  args: ^2.4.2
  freezed: ^3.1.0
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.6
  intl_utils: ^2.8.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
    - family: HarmonyOS_Sans
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
ffigen:
  name: "ClashFFI"
  output: 'lib/clash/generated/clash_ffi.dart'
  headers:
    entry-points:
      - 'libclash/android/arm64-v8a/libclash.h'
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n
